["M.S."]
["M.S.".info]
gpa = "4.02/4.3"
graduation = "2024"

[["M.S.".info.resource]]
href = "https://www.csie.ntust.edu.tw/"
text = "Department Website"

[["M.S.".info.resource]]
href = "https://hsiangjenli.github.io/static/pdf/transcript_ntust.pdf"
text = "Transcript"

[["M.S.".info.resource]]
fontawesome = "fa-brands fa-google-scholar"
href = "https://etheses.lib.ntust.edu.tw/detail/f3738badcd95779cf574e5c3e0d6e43f/"
text = "Graduate Thesis"

["M.S.".english]
location = "Taipei, Taiwan"
major = "Department of Computer Science and Information Engineering"
university = "National Taiwan University of Science and Technology"
# description = ["Big data analytics and information security"]
supervisor = "Chao-Lung Yang & Shan-Hsiang Shen"
thesis = "Temporal Graph Embedding incorporating with Memory Mechanism and k-hop Selection"

["M.S.".chinese]
description = ["大數據分析與資訊安全"]
location = "臺北, 臺灣"
major = "資訊工程學系"
supervisor = "楊朝龍、沈上翔"
thesis = "結合記憶機制以及多躍式選擇於時序圖嵌入"
university = "國立臺灣科技大學"

["B.S."]
["B.S.".info]

gpa = "3.82/4.3"
graduation = "2022"
[["B.S.".info.resource]]
href = "https://banking.nkust.edu.tw/"
text = "Department Website"

[["B.S.".info.resource]]
href = "https://hsiangjenli.github.io/static/pdf/transcript_nkust.pdf"
text = "Transcript"

["B.S.".english]
location = "Kaohsiung, Taiwan"
major = "Department of Money and Banking"
university = "National Kaohsiung University of Science and Technology"

["B.S.".chinese]
location = "高雄, 臺灣"
major = "金融系"
university = "國立高雄科技大學"
