[complex_systems]
    [complex_systems.info]
    tags = ["Recently"]

    [complex_systems.english]
    title = "Complex Systems and Network Science"
    description = ["Unlike grid-like data structures, complex systems are composed by nodes and edges, which are more complicated for analysis and modeling. "]

    [complex_systems.chinese]
    title = "複雜系統"


[metaheuristics]
    [metaheuristics.info]
    tags = ["Future Plan"]

    [metaheuristics.english]
    title = "Metaheuristics"
    description = ["Metaheuristic is a bio-inspired algorithm that can be used to solve optimization problems."]

    [metaheuristics.chinese]
    title = "啟發式演算法"


[distributed_computing]
    [distributed_computing.info]
    tags = ["Future Plan"]

    [distributed_computing.english]
    title = "Distributed Computing"

    [distributed_computing.chinese]
    title = "分散式運算"


[machine_learning_privacy]
    [machine_learning_privacy.info]
    tags = ["Future Plan"]

    [machine_learning_privacy.english]
    title = "Privacy-Preserving Machine Learning"

    [machine_learning_privacy.chinese]
    title = "機器學習資料隱私"
